### ISSUE TITLE
Issue with Nuxt 3 and even Demo Page has issue.

### ISSUE THREAD

**Issue by anuzpandey** [vinayakkulkarni/v-tweakpane#1516]
Theres this issue with the plugin.
`v.addBinding is not a function`

**Comment by calumk** [comment]
The code seems to be fine but the issue is that the NPM release is referencing an old dependancy

` "tweakpane": "^3.1.0"`

If you download the git repo, build it. and then link to the built version, it works as expected.

@vinayakkulkarni  I might be wrong but having read everything, I think You need to bump the package.json version and re-publish

**Comment by vinayakkulkarni** [comment]
https://stackblitz.com/edit/v-tweakpane?file=src/App.vue

Updated [example](https://github.com/vinayakkulkarni/v-tweakpane/tree/main/example) dir as well as stackblitz with latest version!
